arquivos := perm.c heap.c rank.c program.c vetor.c merge.c radix.c shell.c shake.c bubble.c bucket.c radixbin.c insertion.c selection.c quickprimeiro.c quickcentral.c quickmediana3.c quickrecursivoprimeiro.c quickrecursivocentral.c quickrecursivomediana3.c

all: compila
compila:
	gcc $(arquivos) -o program